config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'registrations' }
  root to: 'home#top'
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  get "home/about" => "home#about"

  get "search" => "searches"

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy] do
      # users/:user_id/relarionships/follows　みたいにしたい
      member do
        get 'follows'
        get 'followers'
      end
    end
  end

  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show]
  resources :groups, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    member do
      post 'send_email'
      get 'new_email'
    end
  end

  resource :group_users, only: [:create, :destroy]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  #閲覧数
  is_impressionable counter_cache: true

  #activestorage
  has_one_attached :image

  #この本をいいね舌ユーザーの配列 iranakatta
  #has_many :favorites_users, through: :favorites, source: :user

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search(keyword, matching, user_id)
    case matching
      when "forward" then
        where(["title like ?", "#{keyword}%"])
      when "backward" then
        where(["title like ?", "%#{keyword}"])
      when "exact" then
        where(["title like ?", "#{keyword}"])
      when "partial" then
        where(["title like ?", "%#{keyword}%"])

      #ex9b
      when "day" then
        where(["created_at between ? and ? and user_id like ?", "#{keyword.in_time_zone.at_beginning_of_day}", "#{keyword.in_time_zone.at_end_of_day}", "#{user_id}"])

    end
  end

  def self.search_category(keyword, matching)
    case matching
      when "forward" then
        where(["category like ?", "#{keyword}%"])
      when "backward" then
        where(["category like ?", "%#{keyword}"])
      when "exact" then
        where(["category like ?", "#{keyword}"])
      when "partial" then
        where(["category like ?", "%#{keyword}%"])
    end
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book

end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users

  attachment :image

  validates :name, presence: true
  validates :introduction, presence: true

  def join?(user)
    GroupUser.where(user_id: user.id, group_id: id).exists?
  end

  def owner
    User.find(owner_id)
  end

end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  #140時
  validates :message, presence: true, length: {maximum:140}
  belongs_to :user
  belongs_to :room
end

app/models/relationship.rb
class Relationship < ApplicationRecord
   belongs_to :follower, class_name: "User"
   belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  #DM昨日
  has_many :messages, dependent: :destroy
  has_many :room_users, dependent: :destroy
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  #このユーザーがいいねした本の配列
  #has_many :favorites_books, through: :favorites, source: :book

  # user.followerはRelationshipのfollower_idを参照する
  has_many :follower, class_name:"Relationship", foreign_key:"follower_id", dependent: :destroy
  # user.followedはRelationshipのfollowed_idを参照する
  has_many :followed, class_name:"Relationship", foreign_key:"followed_id", dependent: :destroy

  #この記述もいる
  #user.followsで ユーザーがフォローしてる人一覧　ツイッターでいうフォロー一覧
  has_many :follows, through: :follower, source: :followed
  #user.followersがユーザーがフォローされてる人一覧　ツイッターでいうフォロワー一覧
  has_many :followers, through: :followed, source: :follower

  #DM昨日
  has_many :messages, dependent: :destroy
  has_many :room_users, dependent: :destroy

  #ex7c　グループ
  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users


  attachment :profile_image

  def self.search(keyword, matching, user_id)
    case matching
      when "forward" then
        where(["name like ?", "#{keyword}%"])
      when "backward" then
        where(["name like ?", "%#{keyword}"])
      when "exact" then
        where(["name like ?", "#{keyword}"])
      when "partial" then
        where(["name like ?", "%#{keyword}%"])
    end
  end



end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update, :destroy, :new_email ,:send_email]

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    if @group.save
      redirect_to groups_path(), notice: "You have created group successfully."
    else
      render :new
    end
  end

  def index
    @groups = Group.all
    #.page(params[:page]).reverse_order
  end

  def show
    @group = Group.find(params[:id])
    @comment = Comment.new
  end

  def edit

    #@group = Group.find(params[:id])
    # if @group.owner_id != current_user.id
    #  #@books = current_user.books.page(params[:page]).reverse_order
    #   @groups = Group.all
    #  redirect_to groups_path()
    #end
  end

  def update
    #ensureするのでいらない
    #@group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to group_path(@group.id), notice: "You have updated group successfully."
    else
      render :edit
    end
  end

  def destroy
    #@group = Group.find(params[:id])
    @group.destroy
    redirect_to groups_path, alert: "You have destroyed grup@ successfully"
  end

  def new_email

  end

  def send_email
    #binding.pry
    GroupMailer.notice_event(@group, params[:title], params[:body]).deliver
    flash[:notice] = "Success notice_event. title:#{params[:title]}, body:#{params[:body]}"
    redirect_to group_path(@group.id)
  end

  private

  def group_params
    params.require(:group).permit(:name, :introduction, :image)
  end

  def ensure_correct_user
    @group = Group.find(params[:id])
    unless @group.owner_id == current_user.id
      flash[:alert] = 'error! オーナーでないグループは編集できません'
      redirect_to groups_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/group_users_helper.rb
module GroupUsersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/create.html.erb
<h1>Groups#create</h1>
<p>Find me in app/views/groups/create.html.erb</p>

app/views/groups/edit.html.erb
<p id="notice"></p>
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 p-5 px-sm-3 mx-auto">
      <h1>Group Edit Page</h1>
      <h2>Edit Group</h2>

      <%= form_with model: @group, local: true do |f| %>

        <div class="field my-3">
          <h4><%= f.label :name %></h4>
          <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
        </div>

        <div class="field my-3">
          <h4><label for="inputImage">ProfileImage</label></h4>
          <%= attachment_image_tag @group, :image, :fill, 100, 100, fallback: "no_image.jpg"%><br>
          <%= f.attachment_field :image, placeholder: "グループ画像" %>
        </div>

        <div class="field my-3">
          <h4><%= f.label :introduction %></h4>
          <%= f.text_area :introduction, autocomplete: "introduction" %>
        </div>

        <div class="actions my-3">
          <%= f.submit class:"btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 p-5 px-sm-3 mx-auto">
      <!--<h2>Cancel my account</h2>
      <!--<p>Unhappy? %= button_to "Cancel my account", registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete, class:"btn btn-sm btn-danger" %></p>-->

      <%= link_to "Back", :back %>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
    <%= render 'books/list', user: current_user %>
    </div>

    <div class='col-md-8 offset-md-1'>
      <h2>Groups</h2>

      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th></th>
            <th>name</th>
            <th>introduction</th>
            <th>参加者数</th>
          </tr>
        </thead>
        <tbody>
          <% @groups.each do |g| %>
          <tr>
            <td><%= link_to group_path(g.id) do %>
                <%= attachment_image_tag g, :image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>
                <% end %>
            </td>
            <td><%= g.name %></td>
            <td><%= g.introduction %></td>
            <td><%= g.users.count+1 %></td>
          </tr>
          <%end%>

        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<p id="notice"></p>
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 p-5 px-sm-3 mx-auto">
      <h2 class="mt-3">New Group</h2>
      <%= form_with model: @group, local:true do |f| %>
        <h4>name</h4>
        <%= f.text_field :name %>
        <h4>intro</h4>
        <%= f.text_area :introduction %>

        <h4>ProfileImage</h4>
        <%= f.attachment_field :image, placeholder: "グループ画像" %>

        <div class="my-5">
        <%= f.submit class:"btn btn-success" %>
        </div>
      <% end %>

      <%= link_to "Group Index", groups_path %>
    </div>
  </div>
</div>

app/views/groups/new_email.html.erb
<%= form_with url: send_email_group_path, local:true do |f| %>
  <h4>title</h4>
  <%= f.text_field :title %>
  <h4>body</h4>
  <%= f.text_area :body %>
  <div>
  <%= f.submit "send_email", class:"btn btn-success" %>
  </div>
<% end %>

<%= link_to "Group Page", group_path %>

app/views/groups/show.html.erb
<p id="notice"></p>

<div class="comment-alert">
  <%= render 'comments/alert', comment: @comment %>
</div>

<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <%= render 'books/list', user: current_user %>
    </div>

    <div class='col-md-8 offset-md-1'>
      <h2>Group detail</h2>



      <table class='table table-hover table-inverse'>
        <tbody>
          <tr>
            <td>
              <%= attachment_image_tag @group, :image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>
            </td>
            <td><%= @group.name %></td>
            <td><%= @group.introduction %></td>
            <td>
              <% if @group.owner_id != current_user.id %>
                <% if @group.join?(current_user) %>
                  <%= link_to group_users_path(@group), method: :delete, class:"btn btn-sm btn-danger" do %>
                    Leave this group
                  <% end %>
                <% else %>
                  <%= link_to group_users_path(@group), method: :post, class:"btn btn-sm btn-info" do %>
                    Join this group
                  <% end %>
                <% end %>
              <% end %>
            </td>
            <td><% if @group.owner_id == current_user.id %>
                <%= link_to "Edit", edit_group_path(@group), class:"btn btn-sm btn-success" %>
                <% end %>
            </td>
            <td><% if @group.owner_id == current_user.id %>
                <%= link_to "Destroy", group_path(@group), method: :delete, class:"btn btn-sm btn-danger" %>
                <% end %>
            </td>
          </tr>
        </tbody>
      </table>

      <h4>参加者一覧(<%= @group.users.count+1 %>名)</h4>
        <table class='table table-hover table-inverse'>
            <tr>
              <td><%= link_to user_path(@group.owner) do %>
                    <%= attachment_image_tag @group.owner, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>
                    <% end %>
              </td>
              <td><strong><%= @group.owner.name %>さん（オーナー）</strong></td>
              <td><%= @group.owner.introduction %></td>

            <% @group.users.each do |gu| %>
              <tr>
                <td><%= link_to user_path(gu) do %>
                    <%= attachment_image_tag gu, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>
                    <% end %>
                </td>
                <td><%= gu.name %></td>
                <td><%= gu.introduction %></td>
              </tr>
            <% end %>

        </table>


        <% if @group.owner_id == current_user.id %>
        <h4>notive event</h4>
        <%= link_to "NOTICE EVENT", new_email_group_path, class:"btn btn-primary" %>

        <hr>
        <%end%>

      <%= link_to "Group Index", groups_path %>
    </div>
  </div>
</div>