config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'registrations' }
  root to: 'home#top'
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  get "home/about" => "home#about"

  get "search" => "searches"

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy] do
      # users/:user_id/relarionships/follows　みたいにしたい
      member do
        get 'follows'
        get 'followers'
      end
    end
  end

  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show]
  resources :groups, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    member do
      post 'send_email'
      get 'new_email'
    end
  end

  resource :group_users, only: [:create, :destroy]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  #閲覧数
  is_impressionable counter_cache: true

  #activestorage
  has_one_attached :image

  #この本をいいね舌ユーザーの配列 iranakatta
  #has_many :favorites_users, through: :favorites, source: :user

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search(keyword, matching, user_id)
    case matching
      when "forward" then
        where(["title like ?", "#{keyword}%"])
      when "backward" then
        where(["title like ?", "%#{keyword}"])
      when "exact" then
        where(["title like ?", "#{keyword}"])
      when "partial" then
        where(["title like ?", "%#{keyword}%"])

      #ex9b
      when "day" then
        where(["created_at between ? and ? and user_id like ?", "#{keyword.in_time_zone.at_beginning_of_day}", "#{keyword.in_time_zone.at_end_of_day}", "#{user_id}"])

    end
  end

  def self.search_category(keyword, matching)
    case matching
      when "forward" then
        where(["category like ?", "#{keyword}%"])
      when "backward" then
        where(["category like ?", "%#{keyword}"])
      when "exact" then
        where(["category like ?", "#{keyword}"])
      when "partial" then
        where(["category like ?", "%#{keyword}%"])
    end
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book

end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users

  attachment :image

  validates :name, presence: true
  validates :introduction, presence: true

  def join?(user)
    GroupUser.where(user_id: user.id, group_id: id).exists?
  end

  def owner
    User.find(owner_id)
  end

end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  #140時
  validates :message, presence: true, length: {maximum:140}
  belongs_to :user
  belongs_to :room
end

app/models/relationship.rb
class Relationship < ApplicationRecord
   belongs_to :follower, class_name: "User"
   belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  #DM昨日
  has_many :messages, dependent: :destroy
  has_many :room_users, dependent: :destroy
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  #このユーザーがいいねした本の配列
  #has_many :favorites_books, through: :favorites, source: :book

  # user.followerはRelationshipのfollower_idを参照する
  has_many :follower, class_name:"Relationship", foreign_key:"follower_id", dependent: :destroy
  # user.followedはRelationshipのfollowed_idを参照する
  has_many :followed, class_name:"Relationship", foreign_key:"followed_id", dependent: :destroy

  #この記述もいる
  #user.followsで ユーザーがフォローしてる人一覧　ツイッターでいうフォロー一覧
  has_many :follows, through: :follower, source: :followed
  #user.followersがユーザーがフォローされてる人一覧　ツイッターでいうフォロワー一覧
  has_many :followers, through: :followed, source: :follower

  #DM昨日
  has_many :messages, dependent: :destroy
  has_many :room_users, dependent: :destroy

  #ex7c　グループ
  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users


  attachment :profile_image

  def self.search(keyword, matching, user_id)
    case matching
      when "forward" then
        where(["name like ?", "#{keyword}%"])
      when "backward" then
        where(["name like ?", "%#{keyword}"])
      when "exact" then
        where(["name like ?", "#{keyword}"])
      when "partial" then
        where(["name like ?", "%#{keyword}%"])
    end
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
   @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books.page(params[:page]).reverse_order

    #today_count = @user.books.where(created_at: Time.zone.now.all_day).count
    #@yesterday_count = @user.books.where(created_at: 1.day.ago.all_day).count

    #ex8bから改良
    @count_array = []
    @days_array = []

    for i in 0..6 do
      @count_array[i] = @user.books.where(created_at: i.day.ago.all_day).count
      @days_array[i] = (Time.zone.now-i.day).strftime("%-m/%-d")
    end

    #jsへ飛ばすよう
    gon.count_array = @count_array
    gon.days_array = @days_array

    if @count_array[1] == 0
      @perday = "NONE"
    else
      @perday = (@count_array[0]/@count_array[1].to_f)*100
    end

    @week_count = @user.books.where(created_at: (Time.zone.now.at_beginning_of_day-6.day)..Time.zone.now.at_end_of_day).count
    @lastweek_count = @user.books.where(created_at: (Time.zone.now.at_beginning_of_day-13.day)..(Time.zone.now.at_end_of_day-7.day)).count

    if @lastweek_count == 0
      @perweek = "NONE"
    else
      @perweek = (@week_count/@lastweek_count.to_f)*100
    end

    #binding.pry

  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      @books = current_user.books.page(params[:page]).reverse_order
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/group_users_helper.rb
module GroupUsersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<p id="notice"></p>
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 p-5 px-sm-3 mx-auto">
      <h1>Original User Edit Page</h1>
      <h2>Edit User</h2>

      <%= form_with model: @user, url: user_registration_path, local: true do |f| %>
        <!--%= render "devise/shared/error_messages", resource: resource %-->

        <div class="field my-3">
          <h4><%= f.label :name %></h4>
          <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
        </div>

        <div class="field my-3">
          <h4><label for="inputImage">ProfileImage</label></h4>
          <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg"%><br>
          <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
        </div>

        <div class="field my-3">
          <h4><%= f.label :introduction %></h4>
          <%= f.text_area :introduction, autocomplete: "introduction" %>
        </div>

        <div class="actions my-3">
          <%= f.submit "Update User", class:"btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 p-5 px-sm-3 mx-auto">
      <!--<h2>Cancel my account</h2>
      <!--<p>Unhappy? %= button_to "Cancel my account", registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete, class:"btn btn-sm btn-danger" %></p>-->

      <%= link_to "Back", :back %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<p id="notice"></p>
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
    <%= render 'books/list', user: current_user %>
    </div>

    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= link_to "new group", new_group_path %> | <%= link_to "index group", groups_path %>
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th>follow</th>
            <th>followed</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |u| %>
          <tr>
            <td><%= link_to user_path(u.id) do %>
                <%= attachment_image_tag u, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>
                <% end %>
            </td>
            <td><%= u.name %></td>
            <td><%= link_to follows_user_relationships_path(u), class:"btn btn-outline-primary" do %>
                  <%= u.follower.count %>
                <% end %>
            </td>
            <td><%= link_to followers_user_relationships_path(u), class:"btn btn-outline-primary" do %>
                  <%= u.followed.count %>
                <% end %>
            </td>
            <td>
              <% if u != current_user %>
                <% if current_user.follows.exists?(u.id) %>
                  <%= link_to user_relationships_path(u), method: :delete, class:"btn btn-danger" do %>
                    フォロー解除
                  <% end %>
                <% else %>
                  <%= link_to user_relationships_path(u), method: :post, class:"btn btn-info" do %>
                    フォローする
                  <% end %>
                <% end %>
              <% end %>
            </td>
          </tr>
          <%end%>

        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"></p>
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <%= render 'books/list', user: @user %>
    </div>

    <div class='col-md-8 offset-md-1'>
      <h2>User Info</h2>

      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th>Category</th>
            <th>評価</th>
            <th>いいね</th>
            <th></th>
            <th>閲覧数</th>
          </tr>
        </thead>

        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td><%= link_to user_path(book.user.id) do %>
                  <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>
                <%end%>
            </td>
            <td><%= link_to book_path(book.id) do %>
                  <%= book.title %>
                <%end%>
            </td>
            <td><%= book.body %></td>
            <!--ex9d カテゴリ-->
            <td><%= link_to search_path(keyword: "#{book.category}", table:"category", match: "exact") do %>
                  <%= book.category %>
                <%end%>
            </td>
            <!--評価-->
            <td class="book-evaluation" data-score="<%= book.rate %>"></td>
            <!--いいね機能ついか, 非同期-->
            <td class="favorite-btn-<%= book.id %>">
              <%= render 'favorites/favorite-btn', book: book %>
            </td>
            <td>コメント件数：<%= book.comments.count %></td>
            <td><%= book.impressions_count %></td>
          </tr>
          <%end%>
          <%= paginate @books %>

        </tbody>
      </table>
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th>今日の投稿数</th>
            <th>前日の投稿数</th>
            <th>前日比(%)</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @count_array[0] %></td>
            <td><%= @count_array[1] %></td>
            <td><%= @perday %></td>
          </tr>
        </tbody>
        <thead>
          <tr>
            <th>今週の投稿数</th>
            <th>先週の投稿数</th>
            <th>先週比(%)</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @week_count %></td>
            <td><%= @lastweek_count %></td>
            <td><%= @perweek %></td>
          </tr>
        </tbody>
      </table>
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th>日付</th>
            <% @days_array.each do |d| %>
              <td><%= d %></td>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th>投稿数</th>
            <% @count_array.each do |c| %>
              <td><%= c %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
      <canvas id="myChart"></canvas>
      <script>
      var ctx = document.getElementById("myChart");
      var myChart = new Chart(ctx, {
        type: 'line',
        data: {
          //labels: %= @days_array %>,
          //["2021-10-06 21:46:09 +0900","2021-10-05 21:46:09 +0900","2021-10-04 21:46:09 +0900","2021-10-03 21:46:09 +0900","2021-10-02 21:46:09 +0900","2021-10-01 21:46:09 +0900","2021-09-30 21:46:09 +0900"] %>
          labels: gon.days_array,
          datasets:[{
              label: '投稿数',
              data: gon.count_array,
              backgroundColor: 'rgba(255, 80, 120, 1.0)',
              borderColor: 'rgba(0, 80, 120, 1.0)',
              fill: false
          }]
        },
      });
      </script>

      <div class="count-book">
        <%= render 'searches/result', keyword: @keyword, count_book: @count_book, user_id: @user.id %>
      </div>

    </div>
  </div>
</div>
<script>
  $('.book-evaluation').raty({
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    },
    path: '/assets/'
  });
</script>