config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'registrations' }
  root to: 'home#top'
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  get "home/about" => "home#about"

  get "search" => "searches"

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy] do
      # users/:user_id/relarionships/follows　みたいにしたい
      member do
        get 'follows'
        get 'followers'
      end
    end
  end

  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show]
  resources :groups, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    member do
      post 'send_email'
      get 'new_email'
    end
  end

  resource :group_users, only: [:create, :destroy]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  #閲覧数
  is_impressionable counter_cache: true

  #activestorage
  has_one_attached :image

  #この本をいいね舌ユーザーの配列 iranakatta
  #has_many :favorites_users, through: :favorites, source: :user

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search(keyword, matching, user_id)
    case matching
      when "forward" then
        where(["title like ?", "#{keyword}%"])
      when "backward" then
        where(["title like ?", "%#{keyword}"])
      when "exact" then
        where(["title like ?", "#{keyword}"])
      when "partial" then
        where(["title like ?", "%#{keyword}%"])

      #ex9b
      when "day" then
        where(["created_at between ? and ? and user_id like ?", "#{keyword.in_time_zone.at_beginning_of_day}", "#{keyword.in_time_zone.at_end_of_day}", "#{user_id}"])

    end
  end

  def self.search_category(keyword, matching)
    case matching
      when "forward" then
        where(["category like ?", "#{keyword}%"])
      when "backward" then
        where(["category like ?", "%#{keyword}"])
      when "exact" then
        where(["category like ?", "#{keyword}"])
      when "partial" then
        where(["category like ?", "%#{keyword}%"])
    end
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book

end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users

  attachment :image

  validates :name, presence: true
  validates :introduction, presence: true

  def join?(user)
    GroupUser.where(user_id: user.id, group_id: id).exists?
  end

  def owner
    User.find(owner_id)
  end

end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  #140時
  validates :message, presence: true, length: {maximum:140}
  belongs_to :user
  belongs_to :room
end

app/models/relationship.rb
class Relationship < ApplicationRecord
   belongs_to :follower, class_name: "User"
   belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  #DM昨日
  has_many :messages, dependent: :destroy
  has_many :room_users, dependent: :destroy
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  #このユーザーがいいねした本の配列
  #has_many :favorites_books, through: :favorites, source: :book

  # user.followerはRelationshipのfollower_idを参照する
  has_many :follower, class_name:"Relationship", foreign_key:"follower_id", dependent: :destroy
  # user.followedはRelationshipのfollowed_idを参照する
  has_many :followed, class_name:"Relationship", foreign_key:"followed_id", dependent: :destroy

  #この記述もいる
  #user.followsで ユーザーがフォローしてる人一覧　ツイッターでいうフォロー一覧
  has_many :follows, through: :follower, source: :followed
  #user.followersがユーザーがフォローされてる人一覧　ツイッターでいうフォロワー一覧
  has_many :followers, through: :followed, source: :follower

  #DM昨日
  has_many :messages, dependent: :destroy
  has_many :room_users, dependent: :destroy

  #ex7c　グループ
  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users


  attachment :profile_image

  def self.search(keyword, matching, user_id)
    case matching
      when "forward" then
        where(["name like ?", "#{keyword}%"])
      when "backward" then
        where(["name like ?", "%#{keyword}"])
      when "exact" then
        where(["name like ?", "#{keyword}"])
      when "partial" then
        where(["name like ?", "%#{keyword}%"])
    end
  end



end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_notifications.html.erb
<% flash.each do |key, value| %>
  <% if key=="alert" then col = "danger" else col = "success" end %>
  <p class="alert alert-<%= col %>"><%= value %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= include_gon %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0/dist/Chart.min.js"></script>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to "Bookers2", root_path, class: 'navbar-brand p-2' %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to " Home", user_path(current_user), class: 'fas fa-home nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to ' Users', users_path, class: 'fas fa-users nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to ' Books', books_path, class: 'fas fa-book-open nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to " logout", destroy_user_session_path, method: :delete, class: 'fas fa-sign-out-alt nav-link text-light' %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to " Home", root_path, class: 'fas fa-home nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to ' About', home_about_path, class: 'fas fa-link nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to " sign up", new_user_registration_path, class: 'fas fa-user-plus nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to " login", new_user_session_path, class: 'fas fa-sign-in-alt nav-link text-light' %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>

      <!--検索機能-->
      <% if user_signed_in? %>
      <div class="search-form float-right mx-3">
        <%= form_with url: search_path, method: :get, local: true do |f| %>
          <%= f.text_field :keyword, value: @keyword %>
          <%= f.select :table, [["User", "user"], ["Book", "book"], ["Category", "category"]], {selected: @table}, {} %>
          <%= f.select :match, [["完全一致", "exact"], ["前方一致", "forward"], ["後方一致", "backward"], ["部分一致", "partial"]], {selected: @match}, {} %>
          <%= f.submit "検索" %>
        <% end %>
      </div>
      <% end %>

    </header>
    <main class="mb-auto">
      <%= render 'layouts/notifications' %>
      <%= yield %>
    </main>
    <footer>
      <div class='container mt-5'>
        <div class='row'>
          <div class='mx-auto'>
    	      <!--%= image_tag 'sp.jpeg',  height: '80px', class:"d-block mx-auto" %-->
    	    </div>
    	  </div>
    	  <div class='row'>
      	  <div class='mx-auto'>
      		  <p>CopyRight Infratop.inc</p>
      	  </div>
        </div>
      </div>
    </footer>
  </body>
</html>